### ISSUE TITLE
Animations are sometimes broken

### ISSUE THREAD

**Issue by alex-dev** [Gupyzer0/Spacelines-Kerbalism#15]
`bluedog_OGO_ExperimentBoom_1`animation is broken for sure. I suspect a few other are.

Looking around the code, you just use generic string animation rather than recovering the old experiment animation. I'll try a few MM magic to see If I can make it generically.

Expect a PR soon.

**Comment by Gupyzer0** [comment]
Yep, that's something I expected to happen with some parts. There are some parts that have the right animations patched like "bluedog_foldingMag"that has this patch, check it here -> https://github.com/Gupyzer0/Spacelines-Kerbalism/blob/main/System/ScienceRework/Patches-MagnetometerScan.cfg

```
@PART[bluedog_foldingMag]:NEEDS[Bluedog_DB,FeatureScience]
{
	%MODULE[Experiment]
	{
		@anim_deploy = foldingMag
	}
}
```
Maybe I should put those animations inside the `Support/__Mod name __/` folder but I can wait for your patch first and after that I might do that.

Once again, thanks for the help Alex!

**Comment by alex-dev** [comment]
Ok. So looking at both `DMModuleScienceAnimateGeneric` and `Kerbalism/Experiment`, I can see a few things.
Both support deploy and retract (reverse deploy) animations. Doing a generic patch for it should be easy enough.
Kerbalism also support looping animations... And a few experiments like Nimbus IR radiometer would be really nice with a loop. Those would have to be patched individually.
DMagic supports custom animation speed. That will have to be dropped.
DMagic technically supports to disallow retracting. I don't think this can be done with Kerbalism implementation.

So, I will implement a way to generically set experiment animations according to `DMModuleScienceAnimateGeneric` animation. I'll also consider exposing a way to request a looping animation rather than a deploy/retract.

**Comment by alex-dev** [comment]
```
@PART[*]:HAS[@MODULE[*ModuleScience*]:HAS[#experimentID[bd_ionElec]]]:NEEDS[FeatureScience]:BEFORE[zzzKerbalismDefault]
{
  &MODULE[Experiment]:HAS[#experiment_id[bd_ionElec]]
  {
    &name = Experiment
    &experiment_id = bd_ionElec
  }
}

@PART[*]:HAS[@MODULE[*ModuleScienceAnimate*]:HAS[#experimentID[bd_ionElec]]]:NEEDS[FeatureScience]:FOR[zzzKerbalismDefault]
{
  @MODULE[Experiment]:HAS[~anim_deploy[*]&~anim_loop[*]]
  {
    &anim_deploy = #$../MODULE[*ModuleScienceAnimate*]:HAS[#experimentID[bd_ionElec]]/animationName$
  }
}

@PART[*]:HAS[@MODULE[Experiment]:HAS[#experiment_id[bd_ionElec]]]:NEEDS[FeatureScience]:FOR[zzzKerbalismDefault]
{
  @MODULE[Experiment]:HAS[#experiment_id[bd_ionElec]]
  {
    %data_rate = #$@KERBALISM_EXPERIMENT_VALUES/BDB/bd_ionElec/size$
    @data_rate /= #$@KERBALISM_EXPERIMENT_VALUES/BDB/bd_ionElec/duration$
    %ec_rate = #$@KERBALISM_EXPERIMENT_VALUES/BDB/bd_ionElec/ec_rate$
  }
}

@PART[*]:HAS[@MODULE[*ModuleScience*]:HAS[#experimentID[bd_ionElec]]]:NEEDS[FeatureScience]:AFTER[zzzKerbalismDefault]
{
  !MODULE[*ModuleScience*]:HAS[#experimentID[bd_ionElec]] {}
}
```

Here is what I came up with. If MM supported variables in variables, we could have a truly generic solution. But here we have a pretty straightforward copy and paste for each experiment.

`:BEFORE[zzzKerbalismDefault]` adds barebone experiment module. It supports module being already there, so anything running before can just register a custom experiment module.
`:FOR[zzzKerbalismDefault]` forces science values to be as expected for the experiment (overriding previous values). We can also add any generic patch we want here, such as animation patching.
`:AFTER[zzzKerbalismDefault]` cleanup stock and modded modules.

If you're down with that, I'll rollout on all experiment.
For custom instances, I'll move them into `Support` directory. I may break support for mods other than BDB with this. So this is likely to need more testing.

**Comment by Gupyzer0** [comment]
All right! I like that, go ahead and make the pull request
