### ISSUE TITLE
B9 Fuel Switch Fatal Error

### ISSUE THREAD

**Issue by Redleg1** [Gupyzer0/Spacelines-Kerbalism#19]
HI. I've had an issue when testing out this mod using the branch that you have been frequently updating. I am getting a fatal B9 Fuel Swith error that causes me to have to quit the game. It seems to be related to the Hypergolics patch in the /Support/Benjee10/ folder. When I remove that patch the game loads though there are still several fuel switch related errors. The text of the error mentions that "bdbAZ50NTO" tank type does not exist. Am I missing some file from BDB or something?

**Comment by Gupyzer0** [comment]
Hello Redleg1! thank you for testing out this dev version. Right now I'm thinking on deleting that hypergolics patch but if for the moment you want to try it out you need to install the optional HypergolicBDB patch located in BDB extras folder -> https://github.com/CobaltWolf/Bluedog-Design-Bureau/tree/master/BD_Extras%20(No%20Warranty)/GameData/Bluedog_DB_Extras/Pafftek/HypergolicBDB

I'd guess you're using the development branch. Be aware that the "dev_new_science_order" branch is completely unstable and not tested and that very soon I'll be updating all the science definitions so do not start a career with this for now.

**Comment by Redleg1** [comment]
Awesome thanks for the info!
